### ISSUE TITLE
[Discussion] Pre-phase Analyses

### ISSUE THREAD

**Issue by PeterWang-dev** [PeterWang-dev/arithmetic-problems-generator#1]
Should do pre-phase analyses before architect the software.

## Tasks

- [x] Intergrated Search: Find information as much as you can so that form a entirely sense of the needs.
- [x] Needs Analyze: Classify the needs of users via MoSCoW Method.
- [x] Technical Specifiction: Specify supported platforms, develop tools, library that may be used, etc.
- [x] Requirements modeling: Transfer abstract needs into some reletively concrate functions in order to do architecting.

**Comment by Are-sky** [comment]
### Intergrated Search

**Comment by PeterWang-dev** [comment]
### Need Analyze

#### Must Have

#### Should Have

#### Could Have

#### Won't Have

**Comment by PeterWang-dev** [comment]
### Technical Specification

- **Supported Platform** : Linux, Windows
-  **Programming Language** : Rust
- **Dependencies** :

**Comment by PeterWang-dev** [comment]
### Requirements modeling

**Comment by PeterWang-dev** [comment]
> ### Intergrated Search
> #### 核心模块算法
> 
> [逆波兰表达式](https://zhuanlan.zhihu.com/p/357982040) [在Rust中编写复杂的宏：逆波兰式](https://blog.cloudflare.com/zh-cn/writing-complex-macros-in-rust-reverse-polish-notation-zh-cn/)

题目当中看起来没有样例，能不能找到样例？

**Comment by PeterWang-dev** [comment]
> ### Need Analyze
> #### Must Have
> #### Should Have
> #### Could Have
> #### Won't Have

时间有点紧张了，这两天太忙，这一部分今天之内就得搞定了。

**Comment by PeterWang-dev** [comment]
> ### Requirements modeling

这一部分今天也得搞定

**Comment by Are-sky** [comment]
> > ### Intergrated Search
> > #### 核心模块算法
> > [逆波兰表达式](https://zhuanlan.zhihu.com/p/357982040) [在Rust中编写复杂的宏：逆波兰式](https://blog.cloudflare.com/zh-cn/writing-complex-macros-in-rust-reverse-polish-notation-zh-cn/)
> 
> 题目当中看起来没有样例，能不能找到样例？

什么样例？ 他不是有一个 1 + ( 2 + 3 ) ?

**Comment by PeterWang-dev** [comment]
> ### Need Analyze
> 
> 使用 MoSCoW 方法进行需求分析
> #### Must Have
> 
>     1. 算术题生成器：
>        
>        * 设：
>          
>          * 自然数 n : 0,1,2,⋯ ；
>          * 运算符 op : +,−,×,÷ ；
>          * 括号 : (,) ；
>          * 等号 : = ；
>          * 分隔符 : 空格（用于四则运算符和等号前后）；
>          * 算术表达式 e , e1 , e2 ；
>        * 定义：
>          
>          1. 算术表达式的文法：
>             e = n | e1 op e2 | ( e )
>          2. 四则运算题目: e =
>        
>        首先实现对算术表达式 e = n1 | e1 op e2 的生成与计算支持，
>        其中 n1 为自然数。
> 
>     2. 命令行界面 (CLI, Command-Line Interface) ：
>        
>        * 命令行参数：
>          
>          * `-n` ：生成题目的个数；
>          * `-r` ：生成题目中数值（自然数、真分数和真分数分母）的范围；
>          * `-e` ：题目文件；
>          * `-a` ：答案文件；
> 
>     3. 文件读写：
>        
>        * 读取：读取命令行参数给入的题目文件和答案文件；
>        * 写入：
>          
>          * 生成的题目存入执行程序的当前目录下的 `Exercises.txt` 文件；
>          * 计算出所有题目的答案，并存入执行程序的当前目录下的 `Answers.txt`
>            文件；
>          * 根据给定输入题目和答案，统计分数输出到文件 `Grade.txt`
>            ，格式如下：
>            ```
>            Correct: 5 (1, 3, 5, 7, 9)
>            Wrong: 5 (2, 4, 6, 8, 10)
>            ```
>            
>            
>                
>                  
>                
>            
>                  
>                
>            
>                
>              
>            
>            * `:` 后面的数字 `5` 表示对/错的题目的数量；
>            * 括号（ `(1, 3, 5, 7, 9)` ）内的是对/错题目的编号。
>              为简单起见，假设输入的题目都是按照顺序编号的符合规范的题目。
> 
> 
> #### Should Have
> 
>     1. 算术表达式的生成与计算加入括号（子表达式）和真分数的支持。、
> 
>     2. 算术表达式生成无重复，即任何两道题目不能通过有限次交换 + 和
>        × 左右的算术表达式变换为同一道题目。
> 
>     3. 算术表达式的计算过程中不能出现负数。
> 
>     4. 算术表达式的不能违反数学法则，如除数不能为 0 ， 分数的分母不能为
>        0 ，等等。
> 
> 
> #### Could Have
> 
>     1. 算术表达式的生成与计算关于假分数的支持。
> 
>     2. 通过哈希方法实现缓存计算结果，加速对程序生成的题目的答案的计算。
> 
> 
> #### Won’t Have
> 
> 除了上述的需求，我们不会实现其他的功能。

@Are-sky 检查一下需求分析是否有问题

**Comment by PeterWang-dev** [comment]
> ### Intergrated Search
> 
> 项目的核心需求主要包含两个大部分：算术表达式的生成和计算。 根据核心需求，调研背景知识，了解关于算术表达式生成和计算的相关算法， 检索可能使用到的依赖库。
> 
> 除核心需求外，还需要实现命令行界面和文件读写功能。 因此也需要了解标准库以及其他可能使用到的依赖库。
> #### 算术表达式的生成
> 
> 算术表达式的生成需要使用随机数生成器，有库可供使用：
> 
>     * [rand](https://crates.io/crates/rand) ：Rust 随机数生成库。
> 
> 
> #### 算术表达式的计算
> 
> 关于算术表达式的计算，OI Wiki[1](#user-content-fn-1-f4ba3595e3e3424725b4c81cfd8c1a96) 中有相对详细的介绍。 需要使用到的核心算法是逆波兰表达式求值算法。
> 
> 检索 Rust 的依赖库，有如下库可供使用：
> 
>     * [dc-ock](https://crates.io/crates/dc-ock)
>       ：一个用于计算逆波兰表达式的库。
> 
>     * [prexel](https://crates.io/crates/prexel)
>       ：一个用于计算数学表达式的库。
> 
> 
> #### 分数支持
> 
> 对分数支持，可以使用如下库：
> 
>     * [num](https://crates.io/crates/num) ：Rust 数学库，包含分数类型。
> 
>     * [fraction](https://crates.io/crates/fraction)
>       ：分数库，可用于分数表示。
> 
> 
> #### 去重问题
> 
> 对于重复项的处理，可以考虑使用哈希或者并查集的方法。
> 
> 并查集在 Rust 中有如下库可供使用：
> 
>     * [HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html)
>       ： Rust 标准库中的哈希表。
> 
>     * [union-find](https://crates.io/crates/union-find) ：并查集库。
> 
> 
> #### 命令行界面
> 
> 关于命令行交互，我们使用 Rust 中一个功能丰富且非常常用的库：
> 
>     * [clap](https://crates.io/crates/clap) ：Rust 命令行交互及参数解析库。
> 
> 
> ## Footnotes
> 
>     1. [Z/OL]//表达式求值 - OI Wiki. OI Wiki, 2023.
>        https://oi-wiki.org/misc/expression/. [↩](#user-content-fnref-1-f4ba3595e3e3424725b4c81cfd8c1a96)

我找了相关的库，迅速查阅，看看他们有哪些可以用。下午赶紧定功能，定完功能API就赶紧写了。

**Comment by Are-sky** [comment]
> > ### Intergrated Search
> > 项目的核心需求主要包含两个大部分：算术表达式的生成和计算。 根据核心需求，调研背景知识，了解关于算术表达式生成和计算的相关算法， 检索可能使用到的依赖库。
> > 除核心需求外，还需要实现命令行界面和文件读写功能。 因此也需要了解标准库以及其他可能使用到的依赖库。
> > #### 算术表达式的生成
> > 算术表达式的生成需要使用随机数生成器，有库可供使用：
> > ```
> > * [rand](https://crates.io/crates/rand) ：Rust 随机数生成库。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### 算术表达式的计算
> > 关于算术表达式的计算，OI Wiki[1](#user-content-fn-1-f4ba3595e3e3424725b4c81cfd8c1a96) 中有相对详细的介绍。 需要使用到的核心算法是逆波兰表达式求值算法。
> > 检索 Rust 的依赖库，有如下库可供使用：
> > ```
> > * [dc-ock](https://crates.io/crates/dc-ock)
> >   ：一个用于计算逆波兰表达式的库。
> > 
> > * [prexel](https://crates.io/crates/prexel)
> >   ：一个用于计算数学表达式的库。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### 分数支持
> > 对分数支持，可以使用如下库：
> > ```
> > * [num](https://crates.io/crates/num) ：Rust 数学库，包含分数类型。
> > 
> > * [fraction](https://crates.io/crates/fraction)
> >   ：分数库，可用于分数表示。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### 去重问题
> > 对于重复项的处理，可以考虑使用哈希或者并查集的方法。
> > 并查集在 Rust 中有如下库可供使用：
> > ```
> > * [HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html)
> >   ： Rust 标准库中的哈希表。
> > 
> > * [union-find](https://crates.io/crates/union-find) ：并查集库。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### 命令行界面
> > 关于命令行交互，我们使用 Rust 中一个功能丰富且非常常用的库：
> > ```
> > * [clap](https://crates.io/crates/clap) ：Rust 命令行交互及参数解析库。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Footnotes
> > ```
> > 1. [Z/OL]//表达式求值 - OI Wiki. OI Wiki, 2023.
> >    https://oi-wiki.org/misc/expression/. [↩](#user-content-fnref-1-f4ba3595e3e3424725b4c81cfd8c1a96)
> > ```
> 
> @Are-sky 我找了相关的库，迅速查阅，看看他们有哪些可以用。下午赶紧定功能，定完功能API就赶紧写了。

关于去重问题可参考[实现自动生成四则运算题目的程序](https://blog.csdn.net/WHY995987477/article/details/105294575)
及其[关键代码](https://github.com/King-Authur/-Automatically-generate-four-arithmetic-problems/blob/master/Mathematics/Mathematics/creat.cpp)
